name: freezed_to_objectbox
description: >
  A Dart build tool to generate ObjectBox entity classes from Freezed models automatically.
version: 0.1.0
homepage: https://github.com/yourusername/freezed_to_objectbox
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.4.1
  objectbox: any

dev_dependencies:
  build_runner: ^2.4.8
  freezed_annotation: any
  lints: ^3.0.0
  test: ^1.25.2
  source_gen_test: ^1.0.3

executables:
  freezed_to_objectbox: bin/freezed_to_objectbox.dart
